name: Auto Update VLESS Config

on:
  schedule:
    - cron: '*/15 * * * *' # Автоматический запуск каждые 15 минут
  workflow_dispatch: # Кнопка для ручного запуска в гитхабе

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Дублируем права на запись прямо в сценарии
      
    steps:
    - name: 1. Клонируем репозиторий
      uses: actions/checkout@v4

    - name: 2. Включаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Устанавливаем библиотеку requests
      run: pip install requests

    - name: 4. Запускаем скрипт
      run: python checker.py

    - name: 5. Сохраняем изменения и пушим в репозиторий
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add subscription.txt
        git commit -m "🤖 Авто-обновление 5 серверов VLESS" || echo "Изменений нет"
        git push
