name: Auto Update VLESS Config
on:  
  push: 
    branches: [main]
  schedule: 
    - cron: '7 * * * *'   # каждый час в :07 минут
  workflow_dispatch:

jobs: 
  run-parser: 
    name: Run VLESS Parser 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - name: 1. Клонируем репозиторий 
        uses: actions/checkout@v4 
        
      - name: 2. Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: 3. Зависимости
        run: pip install requests
        
      - name: 4. Устанавливаем xray
        run: |
          curl -sL https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
          unzip -o xray.zip
          chmod +x xray
          ./xray version
          
      - name: 5. Запуск парсера
        run: python checker.py

      - name: 6. Коммит и пуш
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "*.txt"
          git commit -m "🤖 Авто-обновление: рабочие серверы (Германия/Финляндия)" || echo "Изменений нет"
          git push origin main
