name: Auto Update VLESS Config

on:
  schedule:
    - cron: '0 */1 * * *' # Будет запускаться автоматически каждые 6 часов
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Дает право роботу перезаписывать файлы
      
    steps:
    - name: 1. Клонируем репозиторий
      uses: actions/checkout@v4

    - name: 2. Включаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Устанавливаем библиотеку requests
      run: pip install requests

    - name: 4. Запускаем робота
      env:
        # Передаем секретный системный токен внутрь кода Python
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python checker.py
