name: Auto Update VLESS Config

on:
  schedule:
    - cron: '*/5 * * * *' # Авто-запуск каждые 6 часов
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Дает право GitHub Actions делать пуш изменений
      
    steps:
    - name: 1. Клонируем ваш репозиторий (скачиваем checker.py и working_config.json)
      uses: actions/checkout@v4

    - name: 2. Включаем Python на виртуальной машине
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Устанавливаем библиотеку requests
      run: pip install requests

    - name: 4. Запускаем наш скрипт checker.py (он изменит файл на диске)
      run: python checker.py

    - name: 5. Сохраняем изменения и отправляем обратно в ваш GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add subscription.txt
        git commit -m "🤖 Авто-обновление параметров VLESS через GitHub Actions" || echo "Изменений нет"
        git push
